### ISSUE TITLE
Macbook Pro Mid 2010

### ISSUE THREAD

**Issue by nyrob94** [dokterdok/Continuity-Activation-Tool#164] opened 2015-03-31 01:55 UTC
I tried installing the continuity activation tool on my MacBook Pro mid 2010.....it says everything its ok, installs successfully and airdrop now along with Handoff work. I just cant get MacID to work. Any idea why?

Thanks!
Robert

**Comment by dokterdok** [comment] 2015-04-14 12:16
Hi Robert,
This is a known issue with no known workaround, sorry.
Closing (duplicate of #135)

**Closed by dokterdok** 2015-04-14 12:16 UTC
